### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by luisiam**
:construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction: Work In Progress :construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction:

I am able to implement `snapPicture2` as a switch and it returns "some value" which looks legit. However, I don't know where the pictures are stored. I default everything uploading to my NAS via FTP. The pictures are not found on my NAS. May be it only works on SD card? I have no SD card available in my home.

3/2/2016 UPDATE
I figured out that I need to write the return data as a jpeg file. I added `path` to `config.json` defining the directory for snapshots. I also included a new dependency `mkdirp` to create the directory recursively if it doesn't exist. I am too lazy to write the code myself :stuck_out_tongue_closed_eyes: Please review the code and give me some comments :smile:

3/3/2016 UPDATE
Implement issue #6 suggestion. Change `Service` from `MotionSensor` to `SecuritySystem`. State `STAY_ARM` and `NIGHT_ARM` are currently unused. Open for any suggestions.

3/4/2016 UPDATE
Configuration for different state can be customized via `config.json`. Currently support configurable `linkage` (refer to Foscam CGI User Guide) on ring and email only.

:construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction: Work In Progress :construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction:

### CODE REVIEW

**Comment by luisiam** [comment]
#6 Change `Service` from `MotionSensor` to `SecuritySystem`
`STAY_ARM` and `NIGHT_ARM` is currently unused.

**Comment by rooi** [comment]
Nice improvements, thanks!

I think the configuration needs some more states to support my C2.
I did not have time to properly test saving the snapshot

**Comment by luisiam** [comment]
I think you may want to remove the bit mask I added. In the current implementation, I masked off `bit0` and `bit1` from `config.json` and retrieve `bit2` and `bit3` from `getMotionDetectConfig`. Whatever you set in `config.json`, the program will only take `bit0` and `bit1` and apply it. Your `readme` page may be misleading now =]

**Comment by rooi** [comment]
Ah I see, in my quick tests it seemed to work

**Comment by luisiam** [comment]
The current implementation will never change your `bit2` and `bit3`. I think people want to keep `bit2` and `bit3` the same all the time. I just pulled that info from `getMotionDetectConfig`. For your case, the C2, you may also notice that it will always flip `bit7` to `0` since I never know there's a `bit7`.

**Comment by rooi** [comment]
You're right, I missed it in my quick tests (still yet lagged ;)

Don't you think full configuration is better for now? For example, I use the ftp record/snap as file trigger for other scripts (that send video's as iMessage). Being able to turn on and off the record/snap based on the home/away/night functionality you included is very useful for this case I think.
The snapshot switch you included is a very good replacement, but video recording is not implemented as I understand (hope to work on that soon though).

What do you think?

**Comment by luisiam** [comment]
You are right. Other people may want to use the function differently. I am still thinking inside my box lol. Just created a PR to enable full configuration.

I don't see any function to trigger recording on the CGI manual or else I would have implemented that already.

**Comment by rooi** [comment]
I did find a pdf before that describes the a/v protocol, but did not look into it fully:

ftp://109.108.88.53/Nadzor/FOSCAM/SDK%20CGI/MJPEG%20CGI%20SDK/MJPEG%20CGI%20SDK/Ipcamera%20audio%20prototcol.pdf

Perhaps it is something we can use?

**Comment by rooi** [comment]
O wait, that was for another plan to send custom audio to the camera to allow text to speach and such

**Comment by luisiam** [comment]
I am sure we can do that since there's a on-demand record button on the web interface. We just need the latest CGI manual from Foscam.

**Pull request merged**
