### PR TITLE
Support full configuration on linkage

### PR DESCRIPTION
**Pull request by luisiam**
Remove bit mask on linkage configuration and it supports all 4 bits or 8 bits configuration depending on your device.

### CODE REVIEW

**Comment by rooi** [comment]
Thanks!

Have you seen home bridge-people by the way? I'm will try to use it as trigger to set the home/away switch since to homekit geofencing doesn't seems to support multiple persons yet.

**Comment by luisiam** [comment]
I have looked into the plugin. I am not a fan of keep refreshing stuff in the background. The nature that iPhone will disconnect from Wi-Fi from time to time when it's not active makes that method not 100% reliable. The countermeasure for that is the threshold. However, that makes it not real-time and the state will have a delay of 15mins (threshold).

I used a different approach. I wrote the `homebridge-cmdswitch` plugin and use `sed` command to create a database (txt file) storing the state of different switches (people).

I basically created one switch for each person in the house. Based on geofencing of each iPhone (iDevice), it will flip the corresponding switch representing that person. For example, when I leave my house, my iPhone will flip my switch to off. If my wife leaves the house, her iPhone will flip her switch to off.

With those switches, I created characteristic based triggered which will only arm my foscam when all the switches are off (no one is in the house).

**Comment by luisiam** [comment]
The config I used for my plugin is something like this

```
"accessory": "cmdSwitch",
"name": "Luis iPhone",
"on_cmd": "sed -i -re 's/^(Luis:)+.*/\\11/g' ~/.homebridge/occupancy.db",
"off_cmd": "sed -i -re 's/^(Luis:)+.*/\\10/g' ~/.homebridge/occupancy.db",
 "state_cmd": "grep -i 'Luis:1' ~/.homebridge/occupancy.db",
```

In the `occupancy.db`, `Luis:1` means I am home (switch ON) and `Luis:0` means I am not home (switch OFF). When checking the state, it will `grep` `Luis:1` from `occupancy.db` and return `ON` if that line is found. When I leave/arrive home, that switch will be flipped accordingly via geofencing. Hence, changing the line to `Luis:0` or `Luis:1` accordingly.

I have been using that before the `homebridge-people` plugin comes out. Works perfect for me so far.

One trick for this method is that you may need Apple TV to bridge your HomeKit for remote access since the geofencing may be triggered when you are out of your home network.

**Comment by rooi** [comment]
I've tried something like that before, but got stuck at setting geofences for different devices in homekit. I could set a geo-fencing trigger for my phkne of course, but when trying to set it on my wife's phone it showed insufficient priviledges.
Are you using homekit's geo-fencinging triggers, or something else like ifttt

Thanks!

**Comment by luisiam** [comment]
Long story short, I haven't really played with my wife's geofencing feature. Just noticed that she doesn't has permission to set location based triggers. I guess I will have to think of something else.

May be Apple will fix this problem afterwards?

**Comment by luisiam** [comment]
@rooi I am working on simple openHAB dummy switch which can be changed by geofencing using IFTTT. I believe that can solve our problem.

**Comment by rooi** [comment]
Thanks! I was thinking of something similar until apple improves this.

**Comment by luisiam** [comment]
@rooi IFTTT geofencing doesn't seem to be reliable all the time. I wrote a plugin `homebridge-openpaths`. You can take a look and let me know if there's any issue

**Comment by rooi** [comment]
Nice! I try'll give that a try

**Comment by rooi** [comment]
Seems to work well so far. I'll test it some more in the following days. Thanks!

**Comment by luisiam** [comment]
The only problem I am having is that the app won't record your location all the time. It makes sense cox that will drain your battery. Even after your location is recorded, it won't sync to the server immediately. So basically there will be a delay.

**Pull request merged**
